package com.electronicpaymentsinc.prochargelib
import kotlinx.serialization.Serializable

@Serializable
data class RetailMoto (
    var descriptorCodes: String? = "",
    var operatorID: String? = "",
    var retailTerms: String? = "",
    var moto: String? = "",
    var avsZipCode: String? = "",
    var avsAddress: String? = "",
    var taxAmount: String? = "",
    var retailTaxIndicator: String? = "",
    var orderNumber: String? = "",
    var authCharIndicator: String? = "",
    var transactionIdentifier: String? = "",
    var avsResponseCode: String? = "",
    var totalAuthorizedAmount: String? = "",
    var pinBlock: String? = "",
    var cardTypeIndicator: String? = "",
    var cardholderSetCertificate: String? = "",
    var cashBackAmount: String? = "",
    var surCharge: String? = "",
    var ebtVoucherNumber: String? = "",
    var authorizationCode: String? = "",
    var smidID: String? = "",
    var partialAuthIndicator: String? = "",
    var fdrAssignedTPP: String? = "",
    var visaAUAR: String? = "",
    var mcTraceID: String? = "",
    var mcFraudVoidFlag: String? = "",
    var mcFinalAuthIndicator: String? = "",
    var giftCardIndicator: String? = "",
    var transitAccessTermCard: String? = "",
    var mcWalletIdentifier: String? = "",
    var posLaneIDStoreNum: String? = "",
    var merchInitiatedTransIndicator: String? = "",
    var digitalWalletIndicator: String? = "",
    var digitalWalletProgramType: String? = "",
    var visaSpecConditionIndicator: String? = "",
    var deferredAuthIndicator: String? = "",
    var mitAdditionalData: String? = "",
    var citMITIndicator: String? = "",
    var customerCode: String? = "",
    var merchantCertificateSerialNumber: String? = "",
    var cardHolderSetSerialNumber: String? = "",
    var xid: String? = "",
    var transStain: String? = "",
    var mcProgramProtocol: String? = "",
    var mcDirSrvrTransId: String? = "",
    var inAppTokenCrypto: String? = "",
    var remoteCommerceAcceptorId: String? = "",
    var posDataCodes: String? = "",
    var shipToPostalCode: String? = "",
)